name: dialogue_wise
description: Dialoguewise is a headless CMS. This is the client for any of your dart or flutter applications.
homepage: https://dialoguewise.com/
repository: https://github.com/dialoguewise/dart-package
version: 4.0.0

dependencies:
  http: ">=0.13.5 <0.15.0"
  universal_io: ^2.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.1
  test: ^1.14.6
  test_coverage: ^0.5.0
